### ISSUE TITLE
Help Override Color

### ISSUE THREAD

**Issue by TolyanDimov** [primer/github-vscode-theme-dark#1]
Thanks a lot for your branded theme for VSCODE.
I have a little problem, I cannot change the color of the spaces.
`"editor.renderWhitespace": The "Borderly"` parameter displays period in spaces.
Tell me how can I override the color of the dots to be more transparent?

**Comment by simurai** [comment]
You could try to add transparency to `editorWhitespace.foreground`. For example

```
"workbench.colorCustomizations" : {
    "editorWhitespace.foreground": "#444d5677", // makes white space more transparent
},
```

Change the last 2 digits (`77`) to increase or decrease transparency.

**Comment by TolyanDimov** [comment]
> You could try to add transparency to `editorWhitespace.foreground`.

```
"workbench.colorTheme": "GitHub Dark Default",
"workbench.colorCustomizations": {
     "editorWhitespace.foreground": "#30363d",
     "editorRuler.foreground": "#161b22",
},
```
More info here: [Theme Color | Visual Studio Code Extension API](https://code.visualstudio.com/api/references/theme-color)
